spring:
  application:
    name: tracker
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/control
    username: root
    password: Ankit@1992
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

server:
  port: 8080

gmail:
  username: "ankitdungarwal92@gmail.com"
  password: "bqzx utpx doyr gvns"
